"""File fingerprint helpers."""

from __future__ import annotations

from pathlib import Path

from devgraph.core.ids import content_hash


def file_hash(path: Path) -> str:
    try:
        return content_hash(path.read_text(encoding="utf-8", errors="replace"))
    except OSError:
        return content_hash(path.read_bytes())


def is_probably_generated(path: Path, content: str) -> bool:
    name = path.name.lower()
    if name.endswith((".min.js", ".bundle.js", ".map")):
        return True
    head = content[:500].lower()
    return "generated by" in head or "@generated" in head or "do not edit" in head


def is_probably_test(path: Path) -> bool:
    parts = {part.lower() for part in path.parts}
    name = path.name.lower()
    return (
        "test" in parts
        or "tests" in parts
        or name.startswith("test_")
        or name.endswith(("_test.py", ".test.ts", ".spec.ts", ".test.tsx", ".spec.tsx"))
    )
